### ISSUE TITLE
windows编译出错

### ISSUE THREAD

**Issue by safebaseline** [Peony2022/shiro_killer#1]
windows编译出错

**Comment by Underwood12** [comment]
什么错

**Comment by safebaseline** [comment]
/Downloads/shiro_killer-main/main.go:68 +0x879

**Comment by ArthurSun1** [comment]
<img width="973" alt="屏幕截图 2022-05-05 154634" src="https://user-images.githubusercontent.com/42163984/166881552-3dd05b68-6346-400e-b77a-339a52182dcf.png">

**Comment by safebaseline** [comment]
![1651736955(1)](https://user-images.githubusercontent.com/38883009/166881864-14c8e070-c7d2-4547-b640-2a6e2a68ef0b.png)

**Comment by ArthurSun1** [comment]
> ![1651736955(1)](https://user-images.githubusercontent.com/38883009/166881864-14c8e070-c7d2-4547-b640-2a6e2a68ef0b.png)

go版本问题？

**Comment by Underwood12** [comment]
你们不会编译吗？等会我写一下编译教程，我用的mod你tidy就行

**Comment by ArthurSun1** [comment]
> 你们不会编译吗？等会我写一下编译教程，我用的mod你tidy就行

mod的require github.com/panjf2000/ants v1.3.0 这个写的没问题吗

**Comment by ArthurSun1** [comment]
> 你们不会编译吗？等会我写一下编译教程，我用的mod你tidy就行

主要是github.com/panjf2000/ants 没1.3.0啊

**Comment by Underwood12** [comment]
3575139585加这个qq吧
